
name: Push

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: "17"
          cache: gradle
      - name: Build Project
        run: ./gradlew nativeTest
